In [1]:
import numpy as np     
list_ = [ '1' , '2', '3', '4', '5']     
array_list = np.array(object = list_)    

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
type(list_)


list

In [3]:
array_list.astype


<function ndarray.astype>

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [4]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:


In [7]:
array_list = np.array(object = list_, dtype = int)


Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list__ and arra_list. Consider the below code to answer further questions:



In [8]:
import numpy as np                    
num_list = [ [ 1, 2, 3], [4, 5, 6]]        
num_array = np.array(object = num_list)  
for i in num_list:
    if type(i)== list:
        for j in i:print(f'List elements type : {type(j)}')
    else:print(f'List elements type : {type(i)}')
print("---------------------###--------------------")

num_array1 = num_array.flatten()
for i in num_array1:
    print(f'Array element type : {i.dtype}')
#     print(type(i))

List elements type : <class 'int'>
List elements type : <class 'int'>
List elements type : <class 'int'>
List elements type : <class 'int'>
List elements type : <class 'int'>
List elements type : <class 'int'>
---------------------###--------------------
Array element type : int64
Array element type : int64
Array element type : int64
Array element type : int64
Array element type : int64
Array element type : int64


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

In [9]:
display(num_array)
num_array.shape  

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

(ii) size


In [10]:
display(num_array)
num_array.size    

array([[1, 2, 3],
       [4, 5, 6]])

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [12]:
five_ele = np.ones(5)
arr1 = np.diag(five_ele)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr1.shape


(5, 5)